### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by JANCOKRAIMUBAWOK** [developedbyalex/TikTok-MassDownloader#1]
Downloading file:Dendi_nur_hidayat_382799130.mp4
Traceback (most recent call last):
  File "C:\Users\asmar\Downloads\TikTok-MassDownloader-main\main.py", line 153, in <module>
    main()
  File "C:\Users\asmar\Downloads\TikTok-MassDownloader-main\main.py", line 149, in main
    download_video(url["link"], url["description"] + "_" + str(line)[-10:-1] + ".mp4")
  File "C:\Users\asmar\Downloads\TikTok-MassDownloader-main\main.py", line 138, in download_video
    with open("./output/" + file_name, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './output/Dendi_nur_hidayat_382799130.mp4'

**Comment by developedbyalex** [comment]
You need to make a folder called `output`
